'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Termodinámica.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property calor_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calor_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calorespecifico_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calorespecifico_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property direccion_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("direccion_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fondo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fondo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hover_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hover_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hover_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hover_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hoverint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hoverint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hoverlmtd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hoverlmtd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hoversalir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hoversalir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hovertran() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hovertran", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_2_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-2_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_2_031() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-2_031", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_2_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-2_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_2_07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-2_07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_2_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-2_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_2_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-2_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_2_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-2_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_2_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-2_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_2_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-2_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_21_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-21_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_21_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-21_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_3_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-3_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_3_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-3_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_3_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-3_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_3_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-3_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_3_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-3_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_3_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-3_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_3_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-3_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_4_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-4_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_4_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-4_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_4_08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-4_08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_4_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-4_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_4_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-4_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_4_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-4_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_4_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-4_23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_4_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-4_25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_4_27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-4_27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_4_29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-4_29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título_42_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin-título-42_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st_05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st_07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st_08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st_09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Titulo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Titulo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Titulo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Titulo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
